CREATE OR REPLACE VIEW ar AS 
select req.request_id,req.request_based,
  (select rt.requestType_name AS requestType_name from tbl_requesttype rt where rt.requestType_id = req.request_type) AS request_type,
  (select rc.requestCase_name AS requestCase_name from tbl_requestcase rc where rc.requestCase_id = req.request_case) AS request_case,
  req.request_modul,req.request_desc,req.request_reason,req.request_userIdRequested,req.request_userFullNameRequested AS requested_FullName,
  req.request_userEmailRequested AS requested_email,
  date_format(req.request_dateCreated, '%d-%m-%Y %H:%i:%s') AS request_dateCreated,
  (select tbl_user.user_phonePersonal from tbl_user where tbl_user.user_id = req.request_userIdRequested) AS requested_UserPP,
  (select tbl_user.user_phoneOffice from tbl_user where tbl_user.user_id = req.request_userIdRequested) AS requested_UserPO,
  (select tbl_user.user_dept from tbl_user where tbl_user.user_id = req.request_userIdRequested) AS requested_userDept,
  (select tbl_dept.dept_name from tbl_dept where tbl_dept.dept_id = requested_userDept) AS requested_userDeptName,
  (select mgr.dept_mgr_name from tbl_dept_mgr mgr where mgr.dept_id = requested_userDept)as request_mgrDeptName,
  req.request_notification AS request_notification, req.request_notificationRead AS request_notificationRead,
  req.request_PIC AS PIC,
  (select u.user_name from tbl_user u where u.user_id = req.request_PIC) AS PIC_username,
  (select u.user_fullName AS user_fullName from tbl_user u where u.user_id = req.request_PIC) AS PIC_fullname,
  req.request_estimateTime,
  req.request_status AS request_status,
  date_format(req.request_dateDone,'%d-%m-%Y %H:%i:%s') AS request_dateDone,
  req.request_cancel AS request_cancel,req.request_statusReason AS request_statusReason,
  req.request_statusDate,
  (select freq.F_Maintenance from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_Maintenance,
  (select freq.F_Form_req_dev from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_Form_req_dev,
  (select freq.F_Bisnis_proses from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_Bisnis_proses,
  (select freq.F_Regulasi from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_Regulasi,
  (select freq.F_Master_data from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_Master_data,
  (select freq.F_Fungsi_utamaApp from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_Fungsi_utamaApp,
  (select freq.F_Karakteristik_pengguna from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_Karakteristik_pengguna,
  (select freq.F_Prototype from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_Prototype,
  (select freq.F_RAS from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_RAS,
  (select freq.F_UAT from tbl_file_request freq where freq.F_Req_id=req.request_id) as F_UAT
from tbl_request req;